### ISSUE TITLE
json: cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by teddyking** [Nopik/slack-notification-resource#8]
I'm getting a `json: cannot unmarshal number into Go value of type string` error when using the slack resource on concourse v0.75.0.

I've been able to fix this by adding quotes around the `ref:0` in `out`, as follows:

```
jq -n '{version:{ref:"0"}}' >&3
```

Happy to send in a PR if that'd be helpful?

Thanks,
Ed

**Comment by robdimsdale** [comment]
@teddyking this repo doesn't get a lot of attention - suggest you look at https://github.com/cloudfoundry-community/slack-notification-resource instead, where this issue is already fixed.

**Comment by teddyking** [comment]
Ah great, thanks!
